apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: video-generation-service-hpa
  namespace: video-workflow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-generation-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70