apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-generation-service
  namespace: video-workflow
spec:
  replicas: 2  # Start with 2 replicas; scale based on load
  selector:
    matchLabels:
      app: video-generation-service
  template:
    metadata:
      labels:
        app: video-generation-service
    spec:
      containers:
      - name: video-generation-service
        image: video-generation-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017"
        - name: HF_MODEL_ID
          value: "palceholder"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-credentials
              key: hf-token
        resources:
          limits:
            nvidia.com/gpu: 1  # Request 1 GPU per pod
            cpu: "2"
            memory: "8Gi"
          requests:
            cpu: "1"
            memory: "4Gi"
        volumeMounts:
        - name: model-cache
          mountPath: "project/.cache/huggingface"
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: model-cache-pvc